name: appostocosmo
description: Posto Cosmo

publish_to: 'none'

version: 1.1.1+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^1.0.7
  firebase_messaging: ^7.0.3
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0+1
  shared_preferences: ^0.5.12+2
  flutter_offline: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - icone/

flutter_icons:
  android: true
  ios: true
  image_path: "icone/logocosmo.png"
