name: appostocosmo
description: Posto Cosmo

publish_to: 'none'

version: 1.2.0+21

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ffi: ^1.1.2
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.12  
  flutter_webview_plugin: ^0.4.0
  shared_preferences: ^2.0.7
  flutter_offline: ^2.0.0
  file_picker: ^4.0.1
  flutter_chat_ui: ^1.3.3
  uuid: ^3.0.4
  mime: ^1.0.0
  open_file: ^3.2.1
  image_picker: ^0.8.4
  brasil_fields: ^1.1.4
  crypto: ^3.0.1

  # Firebase
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1
  firebase_messaging: ^10.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - icone/

flutter_icons:
  android: true
  ios: true
  image_path: "icone/logocosmo.png"
